### PR TITLE
Adds Examples and Notebooks for Release !

### PR DESCRIPTION
**Pull request by oke-aditya**
- Almost there. 
Just a Checklist of Examples.

All will be in notebooks folder. Also, a py script of them will be available in examples folder!
- [x] Update Readmes
- [x] Quick Start
- [ ] CNNs with Quickvision
- [x] Quantization and training CNNs with Quickvision
- [x] Train a SOTA CNN ! Direct support to PyTorch Image Models
- [x] PyTorch Lightning with Quickvision !
- [x] Object Detection Finetuning FRCNN and Retina Net !
- [x] Object Detection Finetuning with PyTorch Lightning !
- [ ] Object Detection Finetuning with Detr ! (This is tricky !)

I have also initiated ReviewNB. Which will make it easier to view diffs and review Jupyter Notebook.

Contributions and helps to tutorials are welcome.
People can openly review and let me know changes / post changes that you need here !

### CODE REVIEW

**Comment by hassiahk** [comment]
It will be good if we can add an option to open these notebooks in colab. What do you think?

**Comment by ramaneswaran** [comment]
The CNN tutorial notebook looks good, no issues @oke-aditya

**Comment by oke-aditya** [comment]
Object detection is just transfer of Penn fudan example from torchvision.

**Comment by oke-aditya** [comment]
> It will be good if we can add an option to open these notebooks in colab. What do you think?

Would be great. I don't know how to. I will add links to them in md file. You can send a pr for it.

**Comment by hassiahk** [comment]
You can add this line in a markdown cell and replace `notebook-name` with the actual name of the notebook:
```
[![Open All Collab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Quick-AI/quickvision/blob/master/examples/notebooks/<notebook-name>.ipynb)
```

I will send a PR later, you can ignore for now.

**Comment by oke-aditya** [comment]
QAT Training might not work fine, the reason being the way we abstract out models into a sequential block in transfer learning. There mgiht be a fix, but as of now let it be there.

**Pull request merged**
