### PR TITLE
Fixed CSVDataset and Added tests

### PR DESCRIPTION
**Pull request by hassiahk**
Added some tests for CSVDataset. I wanted to check if these tests are fine, that's why created a draft pull request. This also fixes https://github.com/Quick-AI/quickvision/issues/35

### CODE REVIEW

**Comment by oke-aditya** [comment]
Yeah for pandas, It is a testing dependency.
We shouldn't be forcing our users to install pandas with this library.
I will fix this issue of pandas dependency.

**Comment by hassiahk** [comment]
Should I add pandas to the ci-testing.yml?

**Comment by hassiahk** [comment]
@oke-aditya I think I messed up with the merge commits, should I close this and raise a new PR? :(

**Comment by oke-aditya** [comment]
Hmm yes.

**Comment by hassiahk** [comment]
So sorry again, closing this and raising a new one. 

Should I add pandas to the `ci-testing.yml`? That will fix the dependency in testing, right?

**Comment by oke-aditya** [comment]
Nope, I am fixing it in a PR. Please don't. I have a different idea for CI. Simply create a new txt file for test requirements.

**Comment by hassiahk** [comment]
I will create a new `requirements-test.txt` and place the dependencies for testing there. Will that be okay?

**Comment by oke-aditya** [comment]
I have done that in #38 Don't worry 😄

**Comment by hassiahk** [comment]
I think `requirements-dev.txt` is a better name instead of `requirements-test.txt`. Like how it was before. :sweat_smile:. Sorry, if I confused you and that lead to the change in the name.

**Pull request closed without merging**
